-- DB 03
-- P25 ~~ P27 12ro SELECT 쿼리 


--1
SELECT name ,HEIGHT 
FROM T_STUDENT
WHERE HEIGHT >= 180;


--2
SELECT name , weight
FROM T_STUDENT 
WHERE WEIGHT BETWEEN 60 AND 80;

--3
SELECT name ,deptno1
FROM T_STUDENT
WHERE DEPTNO1 IN (101,201);

--4
SELECT NAME 
FROM T_STUDENT 
WHERE NAME 
LIKE '김%';

--5
SELECT NAME , GRADE , HEIGHT 
FROM T_STUDENT 
WHERE grade IN 4 AND HEIGHT > 170;

--6
SELECT NAME ,HEIGHT , WEIGHT 
FROM T_STUDENT 
WHERE GRADE IN 1 OR WEIGHT >=80;

--7 
SELECT NAME , GRADE , HEIGHT , WEIGHT 
FROM T_STUDENT 
WHERE GRADE IN 2 AND HEIGHT > 180 AND WEIGHT > 70 ;

--8
SELECT NAME ,GRADE , HEIGHT , WEIGHT 
FROM T_STUDENT 
WHERE GRADE IN 2 AND ( HEIGHT >180 or WEIGHT >70) ; 

--9
SELECT ENAME , HIREDATE 
FROM T_EMP
WHERE HIREDATE < '1992-01-01' ;

--10
SELECT name, BIRTHDAY , HEIGHT , WEIGHT 
FROM T_STUDENT
WHERE GRADE =1 
ORDER BY BIRTHDAY ASC ;

--11
SELECT name "이름",height "키"
FROM T_STUDENT 
WHERE GRADE =1 
ORDER BY NAME ASC;

--12
SELECT NAME ,BIRTHDAY 
FROM T_EMP2
WHERE BIRTHDAY BETWEEN '1980/01/01' AND '1989/12/31';
